trigger:
- main

pool:
  name: SelfHosted-Local   

variables:
  buildConfiguration: 'Release'
  solution: 'SkyNetApi.sln'               
  webProject: 'SkyNetApi/SkyNetApi.csproj' 

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.x'       

- script: dotnet restore "$(solution)"
  displayName: 'dotnet restore'

- script: dotnet build "$(solution)" -c "$(buildConfiguration)" --no-restore
  displayName: 'dotnet build'

- script: dotnet test "$(solution)" -c "$(buildConfiguration)" --no-build --logger trx
  displayName: 'dotnet test'
  continueOnError: true       

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(webProject)'
    arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
